
import Head from 'next/head'
import Image from 'next/image'
import blueline from '../public/blueline.png'

export default function Home() {
  return (
    <div className='flex flex-col items-center'>
        <Head>
          <title>blueline</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.png" />
        </Head>
        <div className='flex items-center p-4'>
          <Image src={blueline} width={100} height={100} alt={''}> 
          </Image>
          <h1 className= 'text-8xl font-bold bg-gradient-to-r from-slate-950 via-blue-800 to-blue-500 bg-clip-text text-transparent pl-4 text-center' >blueline</h1>
        </div>
    </div>
 

  )

}
